/**
 * Product Catalog Retail Business Attributes API
 * Internal API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Observable } from 'rxjs';
import { AjaxRequest, AjaxResponse } from 'rxjs/ajax';
export declare const BASE_PATH: string;
export interface ConfigurationParameters {
    basePath?: string;
    middleware?: Middleware[];
    username?: string;
    password?: string;
    apiKey?: string | ((name: string) => string);
    accessToken?: string | ((name?: string, scopes?: string[]) => string);
}
export declare class Configuration {
    private configuration;
    constructor(configuration?: ConfigurationParameters);
    get basePath(): string;
    get middleware(): Middleware[];
    get username(): string | undefined;
    get password(): string | undefined;
    get apiKey(): ((name: string) => string) | undefined;
    get accessToken(): ((name: string, scopes?: string[]) => string) | undefined;
}
/**
* This is the base class for all generated API classes.
*/
export declare class BaseAPI {
    protected configuration: Configuration;
    private middleware;
    constructor(configuration?: Configuration);
    withMiddleware: (middlewares: Middleware[]) => this;
    withPreMiddleware: (preMiddlewares: Array<Middleware['pre']>) => this;
    withPostMiddleware: (postMiddlewares: Array<Middleware['post']>) => this;
    protected request<T>(requestOpts: RequestOpts): Observable<T>;
    protected request<T>(requestOpts: RequestOpts, responseOpts?: ResponseOpts): Observable<RawAjaxResponse<T>>;
    private createRequestArgs;
    private rxjsRequest;
    /**
    * Create a shallow clone of `this` by constructing a new instance
    * and then shallow cloning data members.
    */
    private clone;
}
/**
* @deprecated
* export for not being a breaking change
*/
export declare class RequiredError extends Error {
    name: 'RequiredError';
}
export declare const COLLECTION_FORMATS: {
    csv: string;
    ssv: string;
    tsv: string;
    pipes: string;
};
export declare type Json = any;
export declare type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | 'HEAD';
export declare type HttpHeaders = {
    [key: string]: string;
};
export declare type HttpQuery = Partial<{
    [key: string]: string | number | null | boolean | Array<string | number | null | boolean>;
}>;
export declare type HttpBody = Json | FormData;
export interface RequestOpts extends AjaxRequest {
    query?: HttpQuery;
    method: HttpMethod;
    headers?: HttpHeaders;
    body?: HttpBody;
    responseType?: 'json' | 'blob' | 'arraybuffer' | 'text';
}
export interface ResponseOpts {
    respone?: 'raw';
}
export interface OperationOpts {
    responseOpts?: ResponseOpts;
}
export interface RawAjaxResponse<T> extends AjaxResponse {
    response: T;
}
export declare const encodeURI: (value: any) => string;
export declare const querystring: (params: HttpQuery) => string;
/**
* @deprecated
*/
export declare const throwIfRequired: (params: {
    [key: string]: any;
}, key: string, nickname: string) => void;
export declare const throwIfNullOrUndefined: (value: any, paramName: string, nickname: string) => void;
export interface RequestArgs extends AjaxRequest {
}
export interface ResponseArgs extends AjaxResponse {
}
export interface Middleware {
    pre?(request: RequestArgs): RequestArgs;
    post?(response: ResponseArgs): ResponseArgs;
}
